# Generated by Django 5.0 on 2025-05-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaProcess', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images_manipulated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='video_manipulated',
            field=models.IntegerField(default=0),
        ),
    ]
