# Generated by Django 5.0 on 2025-05-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaProcess', '0005_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='process_type',
            field=models.CharField(blank=True, default='default', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
