# Generated by Django 5.0 on 2025-05-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaProcess', '0006_video_process_type_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='transformed_video_file',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
